name: Build Android APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer

      - name: Build with Buildozer
        run: buildozer android debug

      - name: List APK output
        run: ls -la bin/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-debug
          path: bin/*.apk
