name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10-bullseye  # 🧰 Root access, includes apt, python3.10

    env:
      ANDROID_HOME: /github/workspace/android-sdk
      ANDROID_SDK_ROOT: /github/workspace/android-sdk
      PATH: /github/workspace/android-sdk/cmdline-tools/latest/bin:/github/workspace/android-sdk/platform-tools:$PATH

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system packages
        run: |
          apt-get update
          apt-get install -y tar git unzip wget openjdk-17-jdk python3-pip build-essential \
            libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libncurses5-dev \
            libgdbm-dev libnss3-dev libreadline-dev libbz2-dev

      - name: Install Android SDK cmdline tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest

      - name: Accept SDK licenses and install components
        run: |
          apt-get install -y yes
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install Cython virtualenv buildozer

      - name: Ensure buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mp3player-apk
          path: bin/*.apk
