name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip build-essential git zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libncurses5-dev \
            libgdbm-dev libnss3-dev libreadline-dev libbz2-dev

          pip install --upgrade pip
          pip install Cython virtualenv

      - name: Install Buildozer and initialize
        run: |
          pip install buildozer
          buildozer init || echo "buildozer.spec already exists"

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-debug
          path: bin/*.apk
