name: Build Kivy APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.10-bullseye

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:$PATH

    steps:
      - name: Install basic system tools
        run: |
          apt-get update
          apt-get install -y tar git unzip wget openjdk-17-jdk python3-pip build-essential \
            libffi-dev libssl-dev libsqlite3-dev zlib1g-dev libncurses5-dev \
            libgdbm-dev libnss3-dev libreadline-dev libbz2-dev

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Android SDK cmdline tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mv cmdline-tools latest

      - name: Install SDK components and accept licenses
        run: |
          apt-get install -y yes  # just in case it's missing
          yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses
          sdkmanager --sdk_root=${ANDROID_HOME} \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install Cython virtualenv buildozer

      - name: Ensure buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Build APK
        run: buildozer android debug
